USE BugTracker
GO

DROP TABLE Bug
DROP TABLE AppUser
DROP TABLE Role
DROP TABLE Status
DROP TABLE Priority
DROP TABLE Category
GO

CREATE TABLE Status
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL UNIQUE,
    Color NVARCHAR(10) NOT NULL
)
GO

CREATE TABLE Priority
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL UNIQUE,
    Color NVARCHAR(10) NOT NULL
)
GO

CREATE TABLE Category
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL UNIQUE,
    Color NVARCHAR(10) NOT NULL
)
GO

CREATE TABLE Role
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL UNIQUE,
    Color NVARCHAR(10) NOT NULL

)
GO

CREATE TABLE AppUser
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(50) COLLATE Latin1_General_CS_AS NOT NULL UNIQUE,
    UserName NVARCHAR(50) COLLATE Latin1_General_CS_AS NOT NULL UNIQUE,
    Password NVARCHAR(500) COLLATE Latin1_General_CS_AS NOT NULL,
    FirstName NVARCHAR(25) NOT NULL,
    LastName NVARCHAR(25) NOT NULL,
    RoleId INT NULL DEFAULT NULL,
    FOREIGN KEY (RoleId) REFERENCES Role (Id) ON DELETE SET NULL
)
GO

CREATE TABLE Bug
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(50) NOT NULL UNIQUE,
    Description NVARCHAR(255) NOT NULL,
    PriorityId INT NULL,
    StatusId INT NULL,
    CategoryId INT NULL,
    AuthorId INT NULL,
    LastEditorId INT NULL,
    AssigneeId INT NULL,
    CreationDateTime DATETIME NOT NULL DEFAULT GETDATE(),
    LastEditDateTime DATETIME NOT NULL DEFAULT GETDATE(),
    LoggedTime TIME NULL,
    FOREIGN KEY (PriorityId) REFERENCES Priority (Id) ON DELETE SET NULL,
    FOREIGN KEY (StatusId) REFERENCES Status (Id) ON DELETE SET NULL,
    FOREIGN KEY (CategoryId) REFERENCES Category (Id) ON DELETE SET NULL,
    FOREIGN KEY (AuthorId) REFERENCES AppUser (Id) ON DELETE NO ACTION,
    FOREIGN KEY (LastEditorId) REFERENCES AppUser (Id) ON DELETE SET NULL,
    FOREIGN KEY (AssigneeId) REFERENCES AppUser (Id) ON DELETE NO ACTION
)
GO

